### PR TITLE
 Add TensorRT Support and YOLOv5

### PR DESCRIPTION
**Pull request by stefanopini**
Add TensorRT Support from https://github.com/stefanopini/simple-HRNet/pull/99 (in branch tensorrt) to master branch.

- [x] Fix folder structure
- [x] Clean up code
- [x] Update docstrings
- [x] Add missing params
- [x] Test on Colab
- [x] Add documentation
- [x] Add colab link

### CODE REVIEW

**Comment by gpastal24** [comment]
Hi @stefanopini , just checking in. It has come to my attention that there is a new yolov5 release(version 7). When I tried to convert it to trt with the latest version I think there was an error.  version v6.2 worked fine if i remember correctly and it can be loaded by adding :v6.2 in the torch hub str. 

Anyways, I will have free time and I can handle some tasks before the merge, next week if you would like to.

**Comment by stefanopini** [comment]
Hi @gpastal24 , thanks for the update! I've been trying the code on a colab notebook and I should be able to finish working on it soon. I'll try the yolov5 release 7 and switch to the 6.2 if not working.

If you have some time this week, I'll ask you to take a look at the code and test the notebook as soon as they're ready, thank you!

**Comment by stefanopini** [comment]
Hi @gpastal24 , I managed to test the new code and to make the conversion to tensorrt work with the latest yolov5 too! Could you give it a try too?
You can open the notebook in google colab directly using [this link](https://colab.research.google.com/github/stefanopini/simple-HRNet/blob/tensorrt/SimpleHRNet_notebook.ipynb).

**Comment by gpastal24** [comment]
Hello @stefanopini , I tried the notebook . It worked great

**Comment by stefanopini** [comment]
Amazing, thanks for checking! Going to merge soon

**Pull request merged**
